# This is a basic workflow to help you get started with Actions

name: Sync Image to Aliyun  Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git pull
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: crpi-mfzd1wd243t47ks1.cn-hangzhou.personal.cr.aliyuncs.com #注意这里
          username: wpc1016
          password: wpc991016
          logout: false
        
      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          skopeo copy docker://mysql:8.0.18 docker://crpi-mfzd1wd243t47ks1.cn-hangzhou.personal.cr.aliyuncs.com/wpc_1016/mysql:8.0.18
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
